# 公開サイトのルートURL
baseURL = "https://kyo0228.github.io/web/" 

# 言語設定
languageCode = "ja-jp"  
defaultContentLanguage = "ja"

# titleやheder各メタタグ、HomeのH1で使用
title = "Kyo0228 GithubPages"
theme = "hermit"  #ジェネレータでは未使用？

# gitのコミット情報をテンプレートに利用できるフラグ。参考サイト https://baldanders.info/hugo/gitinfo/  
# enableGitInfo = true

# シンタックスハイライトの設定。参考サイト https://monoworks.co.jp/post/2018-07-03-hugo-chroma-syntax-highlighter/
pygmentsCodefences  = true  
pygmentsUseClasses  = true

# 言語が中国語、韓国語、日本語の場合に有効とすることで文字数カウントが正しく動作する
hasCJKLanguage = true 

# RSSフィード内のアイテムの最大数
rssLimit = 10

# RSSのテンプレートでのみ使用されているcopyright文
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." 

# コンテンツで絵文字を有効にする - https://gohugo.io/functions/emojify/
enableEmoji = true

# ga,disqus使う場合に設定
# googleAnalytics = "UA-123-45"
# disqusShortname = "yourdiscussshortname"

# 作者
[author]
  name = "Kyo0228"

# マークダウン記法のライブラリの設定。参考サイト　https://qiita.com/matsuoshi/items/0825a8b37d6ec102f05a
[blackfriday]
  hrefTargetBlank = true  #リンクを別タブへ遷移
  # noreferrerLinks = true
  # nofollowLinks = true

# コンテンツのカテゴリ。 参考サイト https://maku77.github.io/hugo/taxonomy/basic.html
[taxonomies]
  tag = "tags"

[params]
  # 日付フォーマット
  # ※デフォルトから変更。goはフォーマット文字に[2006-01-02 15:04]を使用する
  dateform        = "2006-01-02"
  dateformShort   = "01-02"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  # description = ""
  # images = [""]
  themeColor = "#494f5c"

  #homeSubtitle = "A minimal and fast theme for Hugo."
  homeSubtitle = "Inventory of values and goals"
  footerCopyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
  # bgImg = ""  # Homepage background-image URL

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  # gitUrl = "https://github.com/username/repository/commit/"

  # Toggling this option needs to rebuild SCSS, requires Hugo extended version
  justifyContent = false  # Set "text-align: justify" to `.content`.

  relatedPosts = false  # Add a related content section to all single posts page

  code_copy_button = true # Turn on/off the code-copy-button for code-fields
  
  # Add custom css
  customCSS = ["css/style.css"]

  # Social Icons
  # Check https://github.com/Track3/hermit#social-icons for more info.
  [[params.social]]
    name = "facebook"
    url = "https://twitter.com/"

  [[params.social]]
    name = "instagram"
    url = "https://instagram.com/"

  [[params.social]]
    name = "github"
    url = "https://github.com/"

[menu]

  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10

  [[menu.main]]
    name = "About"
    url = "about-me/"
    weight = 20

